spring.application.name=note-reminder

# Use Render dynamic port
server.port=${PORT:8080}

# SQLite configuration (works locally + on Render)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlite:/app/data/tacocloud.db}
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable H2 (you are NOT using it anymore)
# spring.h2.console.enabled=true   <-- remove or comment

spring.thymeleaf.cache=false